name: Ejecutar Scanner Binance

on:
  workflow_dispatch: # Permite ejecutar el script manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest-eu # Ejecuta sobre servidores Linux europeos/globales

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy ta

    - name: Ejecutar Script de Trading
      run: python scanner.py
